pipeline {
    agent {
        docker {
            image 'maven:3.8.6'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Create Docker Image') {
            steps {
                sh 'docker build -t my-calc-app:latest .'
            }
        }
        stage('Push to Registry') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials']) {
                    sh 'docker push my-calc-app:latest'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'kubectl apply -f calc-deployment.yaml'
            }
        }
    }
}
